name: from_me
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^5.0.0+4
  google_mobile_ads: ^0.13.0
  intl: ^0.17.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Gaegu
      fonts:
        - asset: assets/fonts/Gaegu-Light.ttf
          weight: 400
        - asset: assets/fonts/Gaegu-Regular.ttf
          weight: 700
